disabled_rules:
  - todo

opt_in_rules:
  - force_unwrapping

excluded:
  - .build
  - DerivedData

line_length:
  warning: 120
  error: 150

force_unwrapping:
  severity: warning

force_cast:
  severity: warning

identifier_name:
  min_length: 2
  excluded:
    - id
